### ISSUE TITLE
Implement tests for PolicyVersionDtoProjection component

### ISSUE THREAD

**Issue by mfedkowicz** [asc-lab/java-cqrs-intro#4]
The goal is to implement integration tests using in memory database for `PolicyVersionDtoProjection`component.

**Comment by mmarciniuk** [comment]
@mfedkowicz Hi :)

**Comment by mmarciniuk** [comment]
I just created pull request - https://github.com/asc-lab/java-cqrs-intro/pull/7
@mfedkowicz Can you please review it?
Unfortunately, I don't have permission to link the issue to this pull request.
